### ISSUE TITLE
dependencies vs dependency_injector?

### ISSUE THREAD

**Issue by gtors** [proofit404/dependencies#426] opened 2020-11-23 14:57 UTC
It would be great to have a comparison with other libraries. 

For example, there are [dependecy_injector](https://github.com/ets-labs/python-dependency-injector/). What are the pros and cons against the [dependecy_injector](https://github.com/ets-labs/python-dependency-injector/) ?

**Comment by proofit404** [comment] 2021-01-20 13:25
Duplicate of #341

**Closed by proofit404** 2021-01-20 13:25 UTC
Labels: documentation
